language: minimal

before_script: |
  git clone https://github.com/junegunn/vader.vim.git vader
  git clone https://github.com/tpope/vim-sensible.git sensible

  git clone https://github.com/vim/vim
  pushd vim
  ./configure --with-features=huge
  make -j4
  sudo make install
  popd

script: |
  /usr/local/bin/vim -Nu <(cat << VIMRC
  set rtp^=vader
  set rtp^=.
  set rtp+=sensible
  set expandtab shiftwidth=4 softtabstop=-1
  VIMRC) -c 'Vader! test/*'
